//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpUpdate.LanguageFile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _default() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpUpdate.LanguageFile.default", typeof(_default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnDetails {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnNo {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnYes {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Version: {0} ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_lblNewVersion {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_lblNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Update ist verfügbar! Möchten Sie fortfahren? ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_lblUpdateAvail {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_lblUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Update verfügbar ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} von {1} heruntergeladen ähnelt.
        /// </summary>
        internal static string SharpUpdateDownloadForm_DownloadProgress {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verifiziere Download... ähnelt.
        /// </summary>
        internal static string SharpUpdateDownloadForm_DownloadsFinished {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_DownloadsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update wird heruntergeladen... ähnelt.
        /// </summary>
        internal static string SharpUpdateDownloadForm_lblDownloading {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string SharpUpdateInfoForm_lblDescription {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Update Info ähnelt.
        /// </summary>
        internal static string SharpUpdateInfoForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Derzeitige Version: {0}
        ///Update version: {1} ähnelt.
        /// </summary>
        internal static string SharpUpdateInfoForm_Version {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Update wurde abgebrochen.\nDas Programm wurde nicht modifiziert. ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadCancelled {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Download abgebrochen ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadCancelledTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Problem aufgetreten, beim Herunterladen des Updates.\nVersuchen Sie es später erneut. ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadProblem {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Download Fehler ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadProblemTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadProblemTitle", resourceCulture);
            }
        }
    }
}
