//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpUpdate.LanguageFile {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res_en_En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_en_En() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpUpdate.LanguageFile.Res.en-En", typeof(Res_en_En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnDetails {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnNo {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_btnYes {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Version: {0} ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_lblNewVersion {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_lblNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An update is available!
        ///Would you like to update? ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_lblUpdateAvail {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_lblUpdateAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  - Update Available ähnelt.
        /// </summary>
        internal static string SharpUpdateAcceptForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateAcceptForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloaded {0} of {1} ähnelt.
        /// </summary>
        internal static string SharpUpdateDownloadForm_DownloadProgress {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verifying Download... ähnelt.
        /// </summary>
        internal static string SharpUpdateDownloadForm_DownloadsFinished {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_DownloadsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading Update... ähnelt.
        /// </summary>
        internal static string SharpUpdateDownloadForm_lblDownloading {
            get {
                return ResourceManager.GetString("SharpUpdateDownloadForm_lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string SharpUpdateInfoForm_lblDescription {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Update Info ähnelt.
        /// </summary>
        internal static string SharpUpdateInfoForm_Title {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Version: {0}\nUpdate version: {1} ähnelt.
        /// </summary>
        internal static string SharpUpdateInfoForm_Version {
            get {
                return ResourceManager.GetString("SharpUpdateInfoForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The update download was cancelled.\nThis program has not been modified. ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadCancelled {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Download Cancelled ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadCancelledTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem downloading the update.\nPlease try again later. ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadProblem {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Download Error ähnelt.
        /// </summary>
        internal static string SharpUpdater_DownloadProblemTitle {
            get {
                return ResourceManager.GetString("SharpUpdater_DownloadProblemTitle", resourceCulture);
            }
        }
    }
}
